server:
  port: 8006

spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.25.171
    username: leyou
    password: leyou
    virtual-host: /leyou
  redis:
    host: 192.168.25.171

ly:
  sms:
    accessKeyId: LTAIEoZ2MAneql3W
    accessKeySecret: ZcohHyglongUfnCGM85UgT9HjGhs9u
    signName: 乐优商城 #签名名称
    verifyCodeTemplate: SMS_165415493 #模板Code