server:
  port: 10010

spring:
  application:
    name: ly-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  prefix: /api    #添加路由前缀
  routes:
    item-service: /item/**  # 将商品微服务映射到/item/**
    search-service: /search/**
    upload-service:
      path: /upload/**
      serviceId: upload-service
      strip-prefix: false
    user-service: /user/**
    auth-service: /auth/**
    cart-service: /cart/**
    order-service: /order/**
  add-host-header: true #添加host头信息
  sensitive-headers:    #不添加，所有头都放行

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000   #熔断超时时长5000ms

ribbon:
  ConnectTimeout: 1000  #ribbon链接超时时长
  ReadTimeout: 3500     #ribbon读取超时时长
  MaxAutoRetries: 0     #当前服务重试次数
  MaxAutoRetriesNextServer: 0  #切换服务重试次数

ly:
  jwt:
    pubKeyPath: E:/leyou/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/code
      - /api/item