server:
  port: 8009

spring:
  application:
    name: cart-service
  redis:
    host: 192.168.25.171

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

ly:
  jwt:
    pubKeyPath: E:/leyou/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN