server:
  port: 8005

spring:
  application:
    name: ly-page
  thymeleaf:
    cache: false
  rabbitmq:
    host: 192.168.25.171
    username: leyou
    password: leyou
    virtual-host: /leyou

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka